# build sqld
FROM rust:alpine as builder
RUN apk add --no-cache \
        clang-dev clang llvm-dev \
        build-base tcl protobuf file \
        openssl-dev pkgconfig git cmake \
        musl-dev

WORKDIR /sqld
COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/sqld/target \
    cargo build -p libsql-server --release && \
    cp target/release/sqld /sqld/bin

# runtime
FROM alpine
RUN apk add --no-cache bash su-exec ca-certificates

EXPOSE 5001 8080
VOLUME [ "/var/lib/sqld" ]

RUN addgroup -S -g 666 sqld
RUN adduser -S -u 666 -G sqld -h /var/lib/sqld sqld
WORKDIR /var/lib/sqld
USER sqld

COPY docker-entrypoint.sh /usr/local/bin
COPY docker-wrapper.sh /usr/local/bin

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /sqld/bin /bin/sqld

USER root

ENTRYPOINT ["/usr/local/bin/docker-wrapper.sh"]
CMD ["/bin/sqld"]
